# Generated by Django 3.1.7 on 2021-04-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestionIdeas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='', max_length=255)),
                ('idea_title', models.CharField(default='', max_length=255)),
                ('idea_description', models.TextField(default='')),
                ('idea_picture', models.ImageField(default='', upload_to='idea_pic')),
            ],
        ),
    ]
